name: 'Deploy to AWS S3'
description: 'Deploy some static Javascript to AWS S3'
inputs:
  bucket:
    description: 'S3 bucket name'
    required: true
  bucketRegion:
    description: 'S3 region name'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'Path to the folder containing the deployable files'
    required: true
runs:
  using: 'node16'
  main: 'main.js'
