name: 'Deploy to AWS S3'
description: 'Deploy a static website to AWS S3'
inputs:
   bucket:
    description: 'S3 bucket name'
    required: true
  bucket-region:
    description: 'S3 region name'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'Path to the folder containing the deployable files'
    required: true
outputs:
  website-url:
    description: 'The URL of the deployed website'
runs:
  using: 'docker'
  image: 'Dockerfile'
