name: 'Get & cache dependencies'
description: 'Get the dependencies and cache them for later use'
inputs:
  use-cache:
    description: 'Whether to cache deps or not'
    required: false
    default: 'true'
outputs:
  cached-used:
    description: 'Whether the cache was used'
    value: ${{ steps.install-deps.outputs.cached }}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.use-cache == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install-deps
      if: steps.cache.outputs.cache-hit != 'true' || inputs.use-cache != 'true'
      run: |
        npm ci
        echo "cached=${{ inputs.use-cache }}" >> $GITHUB_OUTPUT
      shell: bash
